name: Lint node

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: "20"

concurrency: ${{github.repository}}-${{ github.workflow }}-${{ github.ref }}

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repo
        uses: actions/checkout@v4

      - id: pnpm
        name: PNPM action setup
        uses: pnpm/action-setup@v4

      - id: setup
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: pnpm

      - id: install
        name: Install dependencies
        run: pnpm i

      - id: eslint
        name: ESLint
        run: pnpm eslint .
      
      - id: prettier
        name: Prettier
        run: pnpm prettier . --check